services:
  frontend:
    image: shipansm/todo-frontend:latest
    container_name: frontend
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:4000
    depends_on:
      - backend
    networks:
      - todo
    env_file:
      - .env
      
  backend:
    image: shipansm/todo-backend:latest
    container_name: backend
    ports:
      - "4000:4000"
    networks:
      - todo
    healthcheck:
      test: curl --fail http://localhost:4000/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 60s
    
    env_file:
      - .env

  web:
    image: shipansm/todo-web:latest
    container_name: web
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - todo

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 150
    networks:
      - todo

networks:
  todo:
    driver: bridge
