services:
  frontend:
    restart: always
    container_name: frontend
    build:
      context: frontend
    depends_on:
      - mongo
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    networks:
      - todo
  backend:
    restart: always
    container_name: backend
    build:
      context: backend
    depends_on:
      - mongo
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env
    networks:
      - todo

  mongo:
    restart: always
    image: mongo
    volumes:
      - mongo_db:/data/db
    expose:
      - 27017
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - todo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: true

    networks:
      - todo
volumes:
  mongo_db: {}
networks:
  todo:
    driver: bridge
