name: todo-javascript-infra
description: todo
runtime:
  name: nodejs
  options:
    typescript: false
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-javascript
  myproject:databaseUser: "shipan"
  myproject:databasePassword: "shipan"
